//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int cardNumber { get; set; }
        public string cardName { get; set; }
        public int cardBalance { get; set; }
    }
}
