//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingInfo()
        {
            this.BookingSeats = new HashSet<BookingSeat>();
        }
    
        public int bookingID { get; set; }
        public int movieScheduleID { get; set; }
        public int noOfTicket { get; set; }
        public int totalPrice { get; set; }
        public string ticketPath { get; set; }
        public string emailAddress { get; set; }
        public string contactNo { get; set; }
        public string memberID { get; set; }
    
        public virtual User User { get; set; }
        public virtual MovieSchedule MovieSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSeat> BookingSeats { get; set; }
    }
}
