//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSeat
    {
        public int bookingSeatID { get; set; }
        public string seatPlace { get; set; }
        public int bookingID { get; set; }
        public int movieScheduleID { get; set; }
    
        public virtual BookingInfo BookingInfo { get; set; }
        public virtual MovieSchedule MovieSchedule { get; set; }
    }
}
