//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public int hallID { get; set; }
        public string hallName { get; set; }
        public int cinemaID { get; set; }
        public string hallType { get; set; }
    
        public virtual Cinema Cinema { get; set; }
    }
}
