//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSchedule()
        {
            this.BookingInfoes = new HashSet<BookingInfo>();
            this.BookingSeats = new HashSet<BookingSeat>();
        }
    
        public int movieScheduleID { get; set; }
        public int movieID { get; set; }
        public int cinemaID { get; set; }
        public int hallID { get; set; }
        public string date { get; set; }
        public int timeslot { get; set; }
        public string movieName { get; set; }
        public string cinemaName { get; set; }
        public int noOfSeatsAvailable { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingInfo> BookingInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSeat> BookingSeats { get; set; }
        public virtual Cinema Cinema { get; set; }
        public virtual Movy Movy { get; set; }
        public virtual MovieSchedule MovieSchedule1 { get; set; }
        public virtual MovieSchedule MovieSchedule2 { get; set; }
    }
}
