//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Team7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransViw
    {
        public int bookingID { get; set; }
        public string movieName { get; set; }
        public string cinemaName { get; set; }
        public int timeslot { get; set; }
        public string date { get; set; }
        public int noOfTicket { get; set; }
        public int totalPrice { get; set; }
    }
}
